language: node_js
node_js:
  - "9"
jobs:
  include:
    - stage: lint
      install: npm install
      before_script:
        - npm install -g gulp-cli
      script: gulp build && npm run lint:less && npm run lint:js
    - stage: test
      install: npm install
      before_script:
        - npm install -g gulp-cli
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script: gulp build && npm run test:unit:travis
