language: node_js
node_js:
  - "9"
jobs:
  include:
    - stage: test
      install: npm install
      services:
        - xvfb
      before_script:
        - npm install -g gulp-cli
        - export DISPLAY=:99.0
      script: gulp build && npm run lint:less && npm run lint:js && npm run test:unit
